spring.application.name=anime-tracker-api
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}